// The apt base shared by Debian and Ubuntu trees. Every name here verified
// present in BOTH debian:trixie and ubuntu:noble via apt-cache (2026-09).
// Anything missing on either distro lives in Common/scripts/debian/ instead:
// vendor repos (docker, ghostty, mise, tailscale, vscode, dbeaver, fastfetch)
// or language installers (cargo/go/npm/pipx tools).
{
	"packages": [
		{
			"action": "install",
			"names": [
				"build-essential",
				"ca-certificates",
				"gnupg",
				"openssl",
				"curl",
				"wget",
				"git",
				"tree",
				"unzip",
				"zip",
				"unrar-free",
				"rsync",
				"gzip",
				"bzip2",
				"cmake",
				"pkg-config",
				"graphviz",
				"xclip",
				"jq",
				"pipx",
				"golang-go",
				"rustup",
				"cargo",
				"nodejs",
				"npm",
				"bat",
				"eza",
				"lazygit",
				"shfmt",
				"fzf",
				"mediainfo",
				"fwupd",
				"ufw",
				"needrestart",
				"openssh-server",
				"cups",
				"cups-pdf",
				"samba",
				"gvfs-backends",
				"libnss-mdns",
				"gnome-keyring",
				"seahorse",
				"gimp",
				"inkscape",
				"libreoffice",
				"mpv",
				"handbrake",
				"gparted",
				"gnome-disk-utility",
				"flameshot",
				"xdotool",
				"yad",
				"x11-utils",
				"neovim",
				"git-delta",
				"7zip",
				"fontconfig",
				"fonts-dejavu",
				"fonts-liberation",
				"fonts-noto-core",
				"fonts-noto-color-emoji",
				"fonts-noto-cjk",
				"fonts-noto-extra",
				"fonts-cascadia-code",
				"fonts-firacode",
				"fonts-jetbrains-mono",
				"steam-installer",
				"virtualbox"
			],
			"package_manager": "apt"
		}
	]
}
