scripts:
  # Commands that require sudo
  - name: disable_time_machine
    action: run
    elevated: true
    content: |
      #!/bin/bash
      sudo tmutil disable

  - name: restart_on_freeze
    action: run
    elevated: true
    content: |
      #!/bin/bash
      sudo systemsetup -setrestartfreeze on

  - name: display_sleep_time
    action: run
    elevated: true
    content: |
      #!/bin/bash
      sudo pmset -a displaysleep 30

  - name: no_sleep_on_ac
    action: run
    elevated: true
    content: |
      #!/bin/bash
      sudo pmset -c sleep 0

  - name: sleep_time_on_battery
    action: run
    elevated: true
    content: |
      #!/bin/bash
      sudo pmset -b sleep 5

  - name: set_standby_delay
    action: run
    elevated: true
    content: |
      #!/bin/bash
      sudo pmset -a standbydelay 86400

  - name: disable_computer_sleep
    action: run
    elevated: true
    content: |
      #!/bin/bash
      sudo systemsetup -setcomputersleep off

  - name: set_hibernate_mode
    action: run
    elevated: true
    content: |
      #!/bin/bash
      sudo pmset -a hibernatemode 0

  - name: expand_file_info_panes
    action: run
    content: |
      #!/bin/bash
      defaults write com.apple.finder FXInfoPanesExpanded -dict General -bool true OpenWith -bool true Privileges -bool true

  - name: disable_itunes_media_keys
    action: run
    content: |
      #!/bin/bash
      launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist
